# For now
name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '>=22'
        cache: yarn

    - run: yarn install
    - run: yarn build
    - run: yarn test-with-coverage
      if: "!contains(github.event.head_commit.message, 'skip test')"

    - name: Deploy to github pages
      uses: crazy-max/ghaction-github-pages@v4.2.0
      with:
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONALACCESSTOKEN }}
      if: "contains(github.ref, 'main')"

    - uses: codecov/codecov-action@v5.5.1
      if: "!contains(github.event.head_commit.message, 'skip test')"
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
