# For now
name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: false
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test-with-coverage
      if: "!contains(github.event.head_commit.message, 'skip test')"

    - name: Deploy to github pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONALACCESSTOKEN }}
      if: github.event_name != "pull_request"

    - uses: codecov/codecov-action@v1
