# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: false
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: deploy to github pages
      run: npm run deploy
